### PR TITLE
#26 - Add Validator methods for domain classes

### PR DESCRIPTION
**Pull request by TheSprtCz**
* Currently I am checking if these statements are true. This changes can invalidate previous data:
   * Topic:
       * `creator` must be `TECH_LEADER`.
       * All `academicSupervisor` must be `AC_SUPERVISOR`.
   * TopicApplication:
       * `techLeader` must be `TECH_LEADER`.
       * `student` must be `STUDENT`.
       * `academicSupervisor` must be `AC_SUPERVISOR`.
    * User:
       * If user is `STUDENT` or `AC_SUPERVISOR` he must have specified `faculty`.
       * If user is `TECH_LEADER` or `COMPANY_REP` he must have specified `company`.
    * Project:
       * All `creators` must be `PROJECT_LEADER`. 
* Validation in `User` is ordered to prevent NullPointerExceptions.
* Configured HK2 to automatically inject DAO classes.
   * Used this [HK2 Bundle](https://github.com/alex-shpak/dropwizard-hk2bundle).
   * All Resources and Validators now use DI injected DAO classes. 
   * Only Authorizers are not automatically injected because of UnitOfAwareProxyFactory.
* Added `@Role` annotation for checking required roles.
   * Validated by `RoleValidator` and `SetRoleValidator` for checking individual user and set of users, respectively.
      * These validators **always** fetch User from DB.
   * This validation is only done on _create_ and _update_ endpoints.
* Updated Swagger documentation.
* Another round of dependency fixes to IntegrationTests.

### CODE REVIEW

**Comment by TheSprtCz** [comment]
Put on hold, because when validating POST request Validation doesn't fetch associated entities resulting in nullPointers.

**Comment by sbunciak** [comment]
@TheSprtCz please add javadocs to validators & validation annotations.

**Comment by sbunciak** [comment]
@TheSprtCz is CreateUpdateChecks group really necessary? Could you please elaborate on the usage?

**Comment by TheSprtCz** [comment]
Well, I was surprised to find how often is entity validated, for example when saving to DB or when fetching from it, also checking roles is "resource heavy" since it has to fetch additional object from DB, so I decided to limit checking roles only when new entity is received, meaning only POST and PUT endpoints. `CreateUpdateChecks` is set up to firstly check all other constraints and after they passed it will check roles. `NotNullChecks` and `ValidationMethodChecks` are there for the similar reason, I check User for proper combination of role and faculty/company, but I cannot do that if one is null, which means that I had to introduce some order to checks, first I check that everything that is required is set up (`NotNullChecks`), then I run all the validation methods (`ValidationMethodChecks`) and last thing I do is I run rest of the tests.

**Comment by TheSprtCz** [comment]
Removed condition for having either company or faculty filled in because is no longer needed. Checking if specific role has either faculty/company is enough.

**Pull request merged**
